version: '3'

services:

  app:
    build: .
    image: expassistant
    restart: always
    container_name: expassistant-cntr
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8081"
    depends_on:
      - postgres-for-app
      - postgres-for-tests

  postgres-for-app:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: expenses_admin
      POSTGRES_PASSWORD: x4pw038g3q049xv9w4hw
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"

  postgres-for-tests:
    image: postgres
    restart: no
    container_name: postgres-tests
    environment:
      POSTGRES_PASSWORD: 01Ef0qz3r8tu5mC0